namespace JobPortal.Domain.Enums
{
    public enum Industry
    {
        Technology,
        Finance,
        Healthcare,
        Education,
        Manufacturing,
        Retail,
        Construction,
        Transportation,
        RealEstate,
        Energy,
        Telecommunications,
        Hospitality,
        Entertainment,
        Agriculture,
        Legal,
        Marketing,
        Insurance,
        Government,
        NonProfit,
        FoodAndBeverage,
        Aerospace,
        Automotive,
        Biotechnology,
        Pharmaceuticals,
        Media,
        Mining,
        Logistics,
        Sports,
        Travel,
        Utilities,
        Consulting,
        Engineering
    }
}
